title: <p align="center"> Sreekanth V. S. </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sreekanth-vs-5150a238">LinkedIn</a> |
  <a href="https://github.com/explorer-sreek">GitHub</a>
  
  <br>   
  I have been working for many big projects at Infosys Ltd. mainly for our client Apple Inc for the last 15+ years.
  <br>
  </p>



theme: jekyll-theme-minimal
